version: '3.8'
services:
  train:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmstrain:latest
    ports:
      - "8001:80"

  dth:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmsdth:latest
    ports:
      - "8003:80"

  movies:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmsmovies:latest
    ports:
      - "8004:80"
