version: '3.8'
services:
  train:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmstrain:latest
    ports:
      - "81:80"

  dth:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmsdth:latest
    ports:
      - "82:80"

  movies:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmsmovies:latest
    ports:
      - "83:80"
