version: '3'
services:
  train:
    image: inthiyazpasha/paytmmstrain:latest
    ports:
      - "80:80"
  dth:
    image: inthiyazpasha/paytmmsdth:latest
    ports:
      - "81:80"
  movies:
    image: inthiyazpasha/paytmmsmovies:latest
    ports:
      - "82:80"

