version: '3.8'
services:
  train:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmstrain:latest
    ports:
      - "8005:80"

  dth:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmsdth:latest
    ports:
      - "8006:80"

  movies:
    deploy:
      replicas: 3
    image: inthiyazpasha/paytmmsmovies:latest
    ports:
      - "8007:80"
